# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
# Author: Sankalp Singh Bais (bash.sankalp@gmail.com)
# Source: https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/
# NOTE: Run below to setup required directories
# sudo mkdir -p /srv/grafana/{data,provisioning} && sudo chown -R 472:472 /srv/grafana/{data,provisioning}

services:
  grafana:
    image: grafana/grafana-enterprise:12.3.0
    container_name: grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SECURITY_ADMIN_PASSWORD=Aur0r@
      - TZ=Asia/Kolkata
    ports:
      - 3000:3000
    volumes:
      - "/srv/grafana/data:/var/lib/grafana"
      - "/srv/grafana/provisioning:/etc/grafana/provisioning"
    restart: unless-stopped
